#!/bin/bash

#SBATCH --partition=gpu_titanrtx_shared_course
#SBATCH --gres=gpu:1
#SBATCH --job-name=AddPackageJob
#SBATCH --ntasks=1
#SBATCH --cpus-per-task=3
#SBATCH --time=00:30:00
#SBATCH --mem=4000M
#SBATCH --output=job_logs/slurm_output_install_package_%A.out

module purge
module load 2021
module load Anaconda3/2021.05

# Your job starts in the directory where you call sbatch
# cd $HOME
cd $HOME/ATCS_group3

#create env
conda env create -f dl2022_gpu.yml
