prompt_templates = {"en": {"SA": {"active": ['Review: {content} \n Is this review positive? Possible answers: \n A yes \n B no \n Answer:',
                                             'Review: {content} \n Does this review sound positive? Possible answers: \n A yes \n B no \n Answer:',
                                             'Review: {content} \n Did the user write a positive review? Possible answers: \n A yes \n B no \n Answer:',
                                             'Review: {content} \n Does this product review reflect positivity? Possible answers: \n A yes \n B no \n Answer:',
                                             'Review: {content} \n Does the user recommend the product? Possible answers: \n A yes \n B no \n Answer:',
                                             'Review: {content} \n Does this product review convey positive sentiment? Possible answers: \n A yes \n B no \n Answer:',
                                             'Review: {content} \n Does this product review have a positive tone? Possible answers: \n A yes \n B no \n Answer:',
                                             'Review: {content} \n Here is a review of a product left by a customer. Do you consider this review to be positive? Possible answers: \n A yes \n B no \n Answer:',
                                             'Review: {content} \n Can you say this review depicts the product in a positive light? Possible answers: \n A yes \n B no \n Answer:',
                                             'Review: {content} \n Does the reviewer express positive sentiment for the product? Possible answers: \n A yes \n B no \n Answer:'
                                             ],
                                  "passive": ['Review: {content} \n Is this review considered positive? Possible answers: \n A yes \n B no \n Answer:',
                                              'Review: {content} \n Is this review regarded to sound positive? Possible answers: \n A yes \n B no \n Answer:',
                                              'Review: {content} \n Was this review written positively by the user? Possible answers: \n A yes \n B no \n Answer:',
                                              'Review: {content} \n Is this product review characterized by positivity? Possible answers: \n A yes \n B no \n Answer:',
                                              'Review: {content} \n Is the review written by the user to recommend the product? Possible answers: \n A yes \n B no \n Answer:',
                                              'Review: {content} \n Is positive sentiment conveyed by this product review? Possible answers: \n A yes \n B no \n Answer:',
                                              'Review: {content} \n Is this review written with a positive tone? Possible answers: \n A yes \n B no \n Answer:',
                                              'Review: {content} \n Here is a review of a product left by a customer. Is this review considered to be positive? Possible answers: \n A yes \n B no \n Answer:',
                                              'Review: {content} \n Can you say the product in this review is depicted in a positive light? Possible answers: \n A yes \n B no \n Answer:',
                                              'Review: {content} \n Is positive sentiment expressed by the reviewer for the product? Possible answers: \n A yes \n B no \n Answer:'
                                              ],
                                  "auxiliary": ['Review: {content} \n Is this review positive? Possible answers: \n A yes \n B no \n Answer:',
                                                'Review: {content} \n Do you consider this review positive? Possible answers: \n A yes \n B no \n Answer:',
                                                'Review: {content} \n Did the user write a positive review? Possible answers: \n A yes \n B no \n Answer:',
                                                'Review: {content} \n Based on this review, does the user recommend the product? Possible answers: \n A yes \n B no \n Answer:',
                                                'Review: {content} \n Does this product review convey positive sentiment? Possible answers: \n A yes \n B no \n Answer:',
                                                'Review: {content} \n Does this product review have a positive tone? Possible answers: \n A yes \n B no \n Answer:',
                                                'Review: {content} \n Here is a review of a product left by a customer. Do you consider this review positive? Possible answers: \n A yes \n B no \n Answer:',
                                                'Review: {content} \n Does the reviewer express positive sentiment for the product? Possible answers: \n A yes \n B no \n Answer:',
                                                'Review: {content} \n Does the user think positively about the product? Possible answers: \n A yes \n B no \n Answer:',
                                                'Review: {content} \n Is positive sentiment expressed in this review? Possible answers: \n A yes \n B no \n Answer:'
                                                ],
                                  "modal": ['Review: {content} \n Could this review be positive? Possible answers: \n A yes \n B no \n Answer:',
                                            'Review: {content} \n Would you consider this review positive? Possible answers: \n A yes \n B no \n Answer:',
                                            'Review: {content} \n Could the user have written a positive review? Possible answers: \n A yes \n B no \n Answer:',
                                            'Review: {content} \n Based on this review, might the user be recommending the product? Possible answers: \n A yes \n B no \n Answer:',
                                            'Review: {content} \n May this product review be conveying positive sentiment? Possible answers: \n A yes \n B no \n Answer:',
                                            'Review: {content} \n Might this product review have a positive tone? Possible answers: \n A yes \n B no \n Answer:',
                                            'Review: {content} \n Here is a review of a product left by a customer. Can you consider this review positive? Possible answers: \n A yes \n B no \n Answer:',
                                            'Review: {content} \n Could the reviewer be expressing positive sentiment for the product? Possible answers: \n A yes \n B no \n Answer:',
                                            'Review: {content} \n Must the user think positively about the product? Possible answers: \n A yes \n B no \n Answer:',
                                            'Review: {content} \n Must positive sentiment be expressed in this review? Possible answers: \n A yes \n B no \n Answer:'
                                            ],
                                  "common": ['Review: {content} \n Do you consider this review to be positive? Possible answers: \n A yes \n B no \n Answer:',
                                             'Review: {content} \n Did the user write a positive review? Possible answers: \n A yes \n B no \n Answer:',
                                             'Review: {content} \n Does the reviewer express positive sentiment for the product? Possible answers: \n A yes \n B no \n Answer:',
                                             'Review: {content} \n Here is a review of a product left by a customer. Can this review be classified as positive? Possible answers: \n A yes \n B no \n Answer:',
                                             'Review: {content} \n Based on this review, could the user be recommending the product? Possible answers: \n A yes \n B no \n Answer:',
                                             'Review: {content} \n Would you say this review is positive? Possible answers: \n A yes \n B no \n Answer:',
                                             'Review: {content} \n Does this product review have a positive tone? Possible answers: \n A yes \n B no \n Answer:'
                                             ],
                                  "rare_synonyms": ['Review: {content} \n Do thou envision this review to be positive? Possible answers: \n A yes \n B no \n Answer:',
                                                    'Review: {content} \n Did the purchaser compose a positive review? Possible answers: \n A yes \n B no \n Answer:',
                                                    'Review: {content} \n Does the reviewer connote a positive disposition towards the product? Possible answers: \n A yes \n B no \n Answer:',
                                                    'Review: {content} \n Here is a review of a commodity fabricated by a purchaser. May this review be categorized as positive? Possible answers: \n A yes \n B no \n Answer:',
                                                    'Review: {content} \n Revolving this review, could the shopper be advocating the product? Possible answers: \n A yes \n B no \n Answer:',
                                                    'Review: {content} \n Would thou hypothesize that the preceding review is positive? Possible answers: \n A yes \n B no \n Answer:',
                                                    'Review: {content} \n Does this commodity review have a positive tenor? Possible answers: \n A yes \n B no \n Answer:'
                                                    ],
                                  "identical_modal": ['Review: {content} \n Can this review be considered positive? Possible answers: \n A yes \n B no \n Answer:',
                                                      'Review: {content} \n Could this review be considered positive? Possible answers: \n A yes \n B no \n Answer:',
                                                      'Review: {content} \n May this review be considered positive? Possible answers: \n A yes \n B no \n Answer:',
                                                      'Review: {content} \n Might this review be considered positive? Possible answers: \n A yes \n B no \n Answer:',
                                                      'Review: {content} \n Shall this review be considered positive? Possible answers: \n A yes \n B no \n Answer:',
                                                      'Review: {content} \n Should this review be considered positive? Possible answers: \n A yes \n B no \n Answer:',
                                                      'Review: {content} \n Will this review be considered positive? Possible answers: \n A yes \n B no \n Answer:',
                                                      'Review: {content} \n Would this review be considered positive? Possible answers: \n A yes \n B no \n Answer:',
                                                      'Review: {content} \n Must this review be considered positive? Possible answers: \n A yes \n B no \n Answer:',
                                                      'Review: {content} \n Ought this review be considered positive? Possible answers: \n A yes \n B no \n Answer:'
                                                      ]},

                           "NLI": {"active": ['Premise: {premise} \n Take this premise as truth. Does this truth entail the following statement: {hypothesis}? Possible answers: \n A yes \n B no \n C maybe \n Answer:',
                                              'Given the premise: {premise} \n Do we assume that this is true: {hypothesis}? Possible answers: \n A yes \n B no \n C maybe \n Answer:',
                                              'Given the premise: {premise} \n Does this premise infer this to be true: {hypothesis}? Possible answers: \n A yes \n B no \n C maybe \n Answer:',
                                              '{premise} \n Can we say that: {hypothesis}? Possible answers: \n A yes \n B no \n C maybe \n Answer:',
                                              'Assume this premise is true: {premise}, \n Therefore, is the following true: {hypothesis}? Possible answers: \n A yes \n B no \n C maybe \n Answer:',
                                              'Premise: {premise} \n Question: Does this premise imply that: {hypothesis}? Possible answers: \n A yes \n B no \n C maybe \n Answer:',
                                              'Suppose this premise is true: {premise} \n Can we infer that: {hypothesis}? Possible answers: \n A yes \n B no \n C maybe \n Answer:',
                                              '{premise} \n Based on the previous passage, does it entail the following: {hypothesis}? Possible answers: \n A yes \n B no \n C maybe \n Answer:',
                                              '{premise} \n Based on the information above, can we infer the following: {hypothesis}? Possible answers: \n A yes \n B no \n C maybe \n Answer:',
                                              'Consider the following: {premise} \n Does the previous text entail the following: {hypothesis}? Possible answers: \n A yes \n B no \n C maybe \n Answer:'
                                              ],
                                   "passive": ['Premise: {premise}, \n This premise is taken as truth. Is the following statement entailed by this truth: {hypothesis}? Possible answers: \n A yes \n B no \n C maybe \n Answer:',
                                               'Given the premise: {premise} \n Is it assumed that this is true {hypothesis}? Possible answers: \n A yes \n B no \n C maybe \n Answer:',
                                               'Given the premise: {premise} \n Is it inferred by this premise for this to be true: {hypothesis}? Possible answers: \n A yes \n B no \n C maybe \n Answer:',
                                               '{premise} \n Can it be said that: {hypothesis}? Possible answers: \n A yes \n B no \n C maybe \n Answer:',
                                               'This premise is assumed to be true: {premise}, \n Therefore, can the following be considered true: {hypothesis}? Possible answers: \n A yes \n B no \n C maybe \n Answer:',
                                               'Premise: {premise} \n Question: Is it implied by this premise that: {hypothesis}? Possible answers: \n A yes \n B no \n C maybe \n Answer:',
                                               'This premise is supposed to be true: {premise} \n Can it be inferred that: {hypothesis}? Possible answers: \n A yes \n B no \n C maybe \n Answer:',
                                               '{premise} \n Based on the previous passage, is the following entailed: {hypothesis}? Possible answers: \n A yes \n B no \n C maybe \n Answer:',
                                               '{premise} \n Based on the information above, can the following be inferred: {hypothesis}? Possible answers: \n A yes \n B no \n C maybe \n Answer:',
                                               'The following is considered: {premise} \n Is the following entailed by the previous text: {hypothesis}? Possible answers: \n A yes \n B no \n C maybe \n Answer:'
                                               ],
                                   "auxiliary": ['Take the following as truth: {premise} \n Does this truth entail the following statement: {hypothesis}? Possible answers: \n A yes \n B no \n C maybe \n Answer:',
                                                 'Given: {premise}, \n Do we assume that it is true that: {hypothesis}? Possible answers: \n A yes \n B no \n C maybe \n Answer:',
                                                 'Assume the following is true: {premise}, \n Therefore, is it entailed that: {hypothesis}? Possible answers: \n A yes \n B no \n C maybe \n Answer:',
                                                 '{premise} \n Question: Does the previous text imply that: {hypothesis}? Possible answers: \n A yes \n B no \n C maybe \n Answer:',
                                                 '{premise} \n Based on the previous passage, is it inferred that: {hypothesis}? Possible answers: \n A yes \n B no \n C maybe \n Answer:',
                                                 '{premise} \n Going from the previous information, is this implied: {hypothesis}? Possible answers: \n A yes \n B no \n C maybe \n Answer:',
                                                 'Take the following as truth: {premise}, \n Is the following statement entailed by this truth: {hypothesis}? Possible answers: \n A yes \n B no \n C maybe \n Answer:',
                                                 'Suppose this is true: {premise}. \n Is it be inferred that: {hypothesis}? Possible answers: \n A yes \n B no \n C maybe \n Answer:',
                                                 'It is assumed true that: {premise} \n Therefore, do we also assume that: {hypothesis}? Possible answers: \n A yes \n B no \n C maybe \n Answer:',
                                                 '{premise} \n Do we say the previous entails the following: {hypothesis}? Possible answers: \n A yes \n B no \n C maybe \n Answer:'
                                                 ],
                                   "modal": ['Take the following as truth: {premise} \n Could this truth entail the following statement: {hypothesis}? Possible answers: \n A yes \n B no \n C maybe \n Answer:',
                                             'Given: {premise} \n Can we assume that it is true that: {hypothesis}? Possible answers: \n A yes \n B no \n C maybe \n Answer:',
                                             'Assume the following must be true: {premise}, \n Therefore, must it be entailed that: {hypothesis}? Possible answers: \n A yes \n B no \n C maybe \n Answer:',
                                             '{premise} \n Question: Would the previous text imply that: {hypothesis}? Possible answers: \n A yes \n B no \n C maybe \n Answer:',
                                             '{premise} \n Based on the previous passage, could it be inferred that: {hypothesis}? Possible answers: \n A yes \n B no \n C maybe \n Answer:',
                                             '{premise} \n Going from the previous information, can this be implied: {hypothesis}? Possible answers: \n A yes \n B no \n C maybe \n Answer:',
                                             'Take the following as truth: {premise}, \n Should the following statement be entailed by this truth: {hypothesis}? Possible answers: \n A yes \n B no \n C maybe \n Answer:',
                                             'Suppose this is true: {premise}. \n Might it be inferred that: {hypothesis}? Possible answers: \n A yes \n B no \n C maybe \n Answer:',
                                             'It is assumed true that: {premise} \n Therefore, ought we also assume that: {hypothesis}? Possible answers: \n A yes \n B no \n C maybe \n Answer:',
                                             '{premise} \n May we say the previous entails the following: {hypothesis}? Possible answers: \n A yes \n B no \n C maybe \n Answer:'
                                             ],
                                   "common": ['Assume it is true that: {premise} \n Therefore, does it also entail: {hypothesis}? Possible answers: \n A yes \n B no \n C maybe \n Answer:',
                                              '{premise} \n Based on that information, is the following claim entailed: {hypothesis}? Possible answers: \n A yes \n B no \n C maybe \n Answer:',
                                              '{premise} \n Question: would this also imply that: {hypothesis}? Possible answers: \n A yes \n B no \n C maybe \n Answer:',
                                              'Suppose {premise} \n Can it be inferred that: {hypothesis}? Possible answers: \n A yes \n B no \n C maybe \n Answer:',
                                              '{premise} \n Based on the previous passage, must the following hold: {hypothesis}? Possible answers: \n A yes \n B no \n C maybe \n Answer:',
                                              'Suppose the following is true: {premise} \n Can we infer that: {hypothesis}? Possible answers: \n A yes \n B no \n C maybe \n Answer:',
                                              'Take the following as truth: {premise} \n could the following statement be entailed by it: {hypothesis}? Possible answers: \n A yes \n B no \n C maybe \n Answer:'
                                              ],
                                   "rare_synonyms": ['Hypothesize the following is truthful: {premise} \n Consequently, does it conjointly entail: {hypothesis}? Possible answers: \n A yes \n B no \n C maybe \n Answer:',
                                                     '{premise} \n Grounded in that information, is the following postulation entailed: {hypothesis}? Possible answers: \n A yes \n B no \n C maybe \n Answer:',
                                                     '{premise} \n Question: would this furthermore signify that {hypothesis}? Possible answers: \n A yes \n B no \n C maybe \n Answer:',
                                                     'Presume {premise} \n Can it be construed that: {hypothesis}? Possible answers: \n A yes \n B no \n C maybe \n Answer:',
                                                     '{premise} \n Proceeding from the aforementioned passage, must the following hold: {hypothesis}? Possible answers: \n A yes \n B no \n C maybe \n Answer:',
                                                     'Presume the ensuing is true: {premise} \n Can we deduce that: {hypothesis}? Possible answers: \n A yes \n B no \n C maybe \n Answer:',
                                                     'Perceive the following as truth: {premise} \n is the following narrative entailed by it: {hypothesis}? Possible answers: \n A yes \n B no \n C maybe \n Answer:'
                                                     ],
                                   "identical_modal": ['Given: {premise} \n Can we assume that: {hypothesis} Possible answers: \n A yes \n B no \n C maybe \n Answer:',
                                                       'Given: {premise} \n Could we assume that: {hypothesis} Possible answers: \n A yes \n B no \n C maybe \n Answer:',
                                                       'Given: {premise} \n May we assume that: {hypothesis} Possible answers: \n A yes \n B no \n C maybe \n Answer:',
                                                       'Given: {premise} \n Might we assume that: {hypothesis} Possible answers: \n A yes \n B no \n C maybe \n Answer:',
                                                       'Given: {premise} \n Shall we assume that: {hypothesis} Possible answers: \n A yes \n B no \n C maybe \n Answer:',
                                                       'Given: {premise} \n Should we assume that: {hypothesis} Possible answers: \n A yes \n B no \n C maybe \n Answer:',
                                                       'Given: {premise} \n Will we assume that: {hypothesis} Possible answers: \n A yes \n B no \n C maybe \n Answer:',
                                                       'Given: {premise} \n Would we assume that: {hypothesis} Possible answers: \n A yes \n B no \n C maybe \n Answer:',
                                                       'Given: {premise} \n Must we assume that: {hypothesis} Possible answers: \n A yes \n B no \n C maybe \n Answer:',
                                                       'Given: {premise} \n Ought we assume that: {hypothesis} Possible answers: \n A yes \n B no \n C maybe \n Answer:'
                                                       ]}},

                    "de": {"SA": {"active": ['Bewertung: {content} \n Ist diese Bewertung positiv? Mögliche Antworten: \n A ja \n B nein \n Antwort:',
                                             'Bewertung: {content} \n Klingt diese Bewertung positiv? Mögliche Antworten: \n A ja \n B nein \n Antwort:',
                                             'Bewertung: {content} \n Hat der Benutzer eine positive Bewertung geschrieben? Mögliche Antworten: \n A ja \n B nein \n Antwort:',
                                             'Bewertung: {content} \n Spiegelt diese Produktbewertung Positivität wider? Mögliche Antworten: \n A ja \n B nein \n Antwort:',
                                             'Bewertung: {content} \n Empfiehlt der Benutzer das Produkt? Mögliche Antworten: \n A ja \n B nein \n Antwort:',
                                             'Bewertung: {content} \n Vermittelt diese Produktbewertung positive Stimmung? Mögliche Antworten: \n A ja \n B nein \n Antwort:',
                                             'Bewertung: {content} \n Hat diese Produktbewertung einen positiven Ton? Mögliche Antworten: \n A ja \n B nein \n Antwort:',
                                             'Bewertung: {content} \n Hier ist eine Bewertung eines Produkts, die von einem Kunden abgegeben wurde. Halten Sie diese Bewertung für positiv? Mögliche Antworten: \n A ja \n B nein \n Antwort:',
                                             'Bewertung: {content} \n Kann man sagen, dass diese Bewertung das Produkt positiv darstellt? Mögliche Antworten: \n A ja \n B nein \n Antwort:',
                                             'Bewertung: {content} \n Drückt der Bewerter positive Stimmung für das Produkt aus? Mögliche Antworten: \n A ja \n B nein \n Antwort:'
                                             ],
                                  "passive": ['Bewertung: {content} \n Wird diese Bewertung als positiv angesehen? Mögliche Antworten: \n A ja \n B nein \n Antwort:',
                                              'Bewertung: {content} \n Wird diese Bewertung als positiv betrachtet? Mögliche Antworten: \n A ja \n B nein \n Antwort:',
                                              'Bewertung: {content} \n Wurde diese Bewertung positiv vom Benutzer geschrieben? Mögliche Antworten: \n A ja \n B nein \n Antwort:',
                                              'Bewertung: {content} \n Wird diese Produktbewertung als positiv charakterisiert? Mögliche Antworten: \n A ja \n B nein \n Antwort:',
                                              'Bewertung: {content} \n Wird die Bewertung vom Benutzer empfohlen, um das Produkt zu kaufen? Mögliche Antworten: \n A ja \n B nein \n Antwort:',
                                              'Bewertung: {content} \n Wird durch diese Produktbewertung positive Stimmung vermittelt? Mögliche Antworten: \n A ja \n B nein \n Antwort:',
                                              'Bewertung: {content} \n Wird durch diese Bewertung ein positiver Ton vermittelt? Mögliche Antworten: \n A ja \n B nein \n Antwort:',
                                              'Bewertung: {content} \n Hier ist eine Bewertung eines Produkts, die von einem Kunden abgegeben wurde. Wird diese Bewertung als positiv angesehen? Mögliche Antworten: \n A ja \n B nein \n Antwort:',
                                              'Bewertung: {content} \n Kann man sagen, dass das Produkt in dieser Bewertung positiv dargestellt wird? Mögliche Antworten: \n A ja \n B nein \n Antwort:',
                                              'Bewertung: {content} \n Wird positive Stimmung für das Produkt vom Bewerter ausgedrückt? Mögliche Antworten: \n A ja \n B nein \n Antwort:'
                                              ],
                                  "auxiliary": ["Bewertung: {content} \n Drückt diese Bewertung positive Stimmung aus? Mögliche Antworten: \n A ja \n B nein \n Antwort:",
                                                "Bewertung: {content} \n Betrachten Sie diese Bewertung als positiv? Mögliche Antworten: \n A ja \n B nein \n Antwort:",
                                                "Bewertung: {content} \n Hat der Benutzer eine positive Bewertung geschrieben? Mögliche Antworten: \n A ja \n B nein \n Antwort:",
                                                "Bewertung: {content} \n Empfiehlt der Benutzer das Produkt aufgrund dieser Bewertung? Mögliche Antworten: \n A ja \n B nein \n Antwort:",
                                                "Bewertung: {content} \n Vermittelt diese Produktbewertung positive Stimmung? Mögliche Antworten: \n A ja \n B nein \n Antwort:",
                                                "Bewertung: {content} \n Hat diese Produktbewertung einen positiven Ton? Mögliche Antworten: \n A ja \n B nein \n Antwort:",
                                                "Bewertung: {content} \n Hier ist eine Bewertung eines Produkts, die von einem Kunden abgegeben wurde. Betrachten Sie diese Bewertung als positiv? Mögliche Antworten: \n A ja \n B nein \n Antwort:",
                                                "Bewertung: {content} \n Drückt der Bewerter positive Stimmung für das Produkt aus? Mögliche Antworten: \n A ja \n B nein \n Antwort:",
                                                "Bewertung: {content} \n Denkt der Benutzer positiv über das Produkt? Mögliche Antworten: \n A ja \n B nein \n Antwort:",
                                                "Bewertung: {content} \n Wird in dieser Bewertung positive Stimmung ausgedrückt? Mögliche Antworten: \n A ja \n B nein \n Antwort:"
                                                ],
                                  "modal": ["Bewertung: {content} \n Könnte diese Bewertung positiv sein? Mögliche Antworten: \n A ja \n B nein \n Antwort:",
                                            "Bewertung: {content} \n Würden Sie diese Bewertung als positiv betrachten? Mögliche Antworten: \n A ja \n B nein \n Antwort:",
                                            "Bewertung: {content} \n Könnte der Benutzer eine positive Bewertung geschrieben haben? Mögliche Antworten: \n A ja \n B nein \n Antwort:",
                                            "Bewertung: {content} \n Könnte der Benutzer aufgrund dieser Bewertung das Produkt empfehlen? Mögliche Antworten: \n A ja \n B nein \n Antwort:",
                                            "Bewertung: {content} \n Könnte diese Produktbewertung positive Stimmung vermitteln? Mögliche Antworten: \n A ja \n B nein \n Antwort:",
                                            "Bewertung: {content} \n Könnte diese Produktbewertung einen positiven Ton haben? Mögliche Antworten: \n A ja \n B nein \n Antwort:",
                                            "Bewertung: {content} \n Hier ist eine Bewertung eines Produkts, die von einem Kunden abgegeben wurde. Können Sie diese Bewertung als positiv betrachten? Mögliche Antworten: \n A ja \n B nein \n Antwort:",
                                            "Bewertung: {content} \n Könnte der Bewerter positive Stimmung für das Produkt ausdrücken? Mögliche Antworten: \n A ja \n B nein \n Antwort:",
                                            "Bewertung: {content} \n Muss der Benutzer positiv über das Produkt denken? Mögliche Antworten: \n A ja \n B nein \n Antwort:",
                                            "Bewertung: {content} \n Muss in dieser Bewertung positive Stimmung ausgedrückt werden? Mögliche Antworten: \n A ja \n B nein \n Antwort:"
                                            ],
                                  "common": ["Bewertung: {content} \n Betrachten Sie diese Bewertung als positiv? Mögliche Antworten: \n A ja \n B nein \n Antwort:",
                                             "Bewertung: {content} \n Hat der Benutzer eine positive Bewertung geschrieben? Mögliche Antworten: \n A ja \n B nein \n Antwort:",
                                             "Bewertung: {content} \n Drückt der Rezensent positive Stimmung für das Produkt aus? Mögliche Antworten: \n A ja \n B nein \n Antwort:",
                                             "Bewertung: {content} \n Hier ist eine Bewertung eines Produkts, die von einem Kunden hinterlassen wurde. Kann diese Bewertung als positiv eingestuft werden? Mögliche Antworten: \n A ja \n B nein \n Antwort:",
                                             "Bewertung: {content} \n Könnte der Benutzer basierend auf dieser Bewertung das Produkt empfehlen? Mögliche Antworten: \n A ja \n B nein \n Antwort:",
                                             "Bewertung: {content} \n Würden Sie sagen, dass diese Bewertung positiv ist? Mögliche Antworten: \n A ja \n B nein \n Antwort:",
                                             "Bewertung: {content} \n Hat diese Produktbewertung einen positiven Ton? Mögliche Antworten: \n A ja \n B nein \n Antwort:"
                                             ],
                                  "rare_synonyms": ["Bewertung: {content} \n Begutachtest du diese Bewertung als bejahend? Mögliche Antworten: \n A ja \n B nein \n Antwort:",
                                                    "Bewertung: {content} \n Hat der Käufer eine positive Bewertung verfasst? Mögliche Antworten: \n A ja \n B nein \n Antwort:",
                                                    "Bewertung: {content} \n Drückt der Rezensent eine positive Haltung gegenüber dem Produkt aus? Mögliche Antworten: \n A ja \n B nein \n Antwort:",
                                                    "Bewertung: {content} \n Hier ist eine Bewertung eines Fabrikat, die von einem Käufer kreiert wurde. Kann diese Bewertung als positiv kategorisiert werden? Mögliche Antworten: \n A ja \n B nein \n Antwort:",
                                                    "Bewertung: {content} \n Drehend diese Bewertung, könnte der Käufer das Produkt befürworten? Mögliche Antworten: \n A ja \n B nein \n Antwort:",
                                                    "Bewertung: {content} \n Würdest du vermuten, dass die vorherige Bewertung positiv ist? Mögliche Antworten: \n A ja \n B nein \n Antwort:",
                                                    "Bewertung: {content} \n Hat diese Warenbewertung eine positive Ausrichtung? Mögliche Antworten: \n A ja \n B nein \n Antwort:"
                                                    ],
                                  "identical_modal": ["Bewertung: {content} \n Dürfen diese Bewertung als positiv betrachtet werden? Mögliche Antworten: \n A ja \n B nein \n Antwort:",
                                                      "Bewertung: {content} \n Können diese Bewertung als positiv betrachtet werden? Mögliche Antworten: \n A ja \n B nein \n Antwort:",
                                                      "Bewertung: {content} \n Möchten diese Bewertung als positiv betrachtet werden? Mögliche Antworten: \n A ja \n B nein \n Antwort:",
                                                      "Bewertung: {content} \n Müssen diese Bewertung als positiv betrachtet werden? Mögliche Antworten: \n A ja \n B nein \n Antwort:",
                                                      "Bewertung: {content} \n Wollen diese Bewertung als positiv betrachtet werden? Mögliche Antworten: \n A ja \n B nein \n Antwort:",
                                                      "Bewertung: {content} \n Sollen diese Bewertung als positiv betrachtet werden? Mögliche Antworten: \n A ja \n B nein \n Antwort:"
                                                      ]},

                           "NLI": {"active": ['Prämisse: {premise} \n Nehmen Sie diese Prämisse als Wahrheit an. Impliziert diese Wahrheit die folgende Aussage: {hypothesis}? Mögliche Antworten: \n A ja \n B nein \n C vielleicht \n Antwort:',
                                              'Gegeben die Prämisse: {premise} \n Gehen wir davon aus, dass dies wahr ist: {hypothesis}? Mögliche Antworten: \n A ja \n B nein \n C vielleicht \n Antwort:',
                                              'Gegeben die Prämisse: {premise} \n Impliziert diese Prämisse, dass dies wahr ist: {hypothesis}? Mögliche Antworten: \n A ja \n B nein \n C vielleicht \n Antwort:',
                                              '{premise} \n Können wir sagen, dass: {hypothesis}? Mögliche Antworten: \n A ja \n B nein \n C vielleicht \n Antwort:',
                                              'Nehmen Sie diese Prämisse als wahr an: {premise}, \n Ist dann das Folgende wahr: {hypothesis}? Mögliche Antworten: \n A ja \n B nein \n C vielleicht \n Antwort:',
                                              'Prämisse: {premise} \n Frage: Impliziert diese Prämisse, dass: {hypothesis}? Mögliche Antworten: \n A ja \n B nein \n C vielleicht \n Antwort:',
                                              'Nehmen wir an, diese Prämisse ist wahr: {premise} \n Können wir daraus schließen, dass: {hypothesis}? Mögliche Antworten: \n A ja \n B nein \n C vielleicht \n Antwort:',
                                              '{premise} \n Basierend auf dem vorherigen Abschnitt, impliziert es das Folgende: {hypothesis}? Mögliche Antworten: \n A ja \n B nein \n C vielleicht \n Antwort:',
                                              '{premise} \n Basierend auf den obigen Informationen, können wir daraus schließen, dass: {hypothesis}? Mögliche Antworten: \n A ja \n B nein \n C vielleicht \n Antwort:',
                                              'Betrachten Sie Folgendes: {premise} \n Impliziert der vorherige Text das Folgende: {hypothesis}? Mögliche Antworten: \n A ja \n B nein \n C vielleicht \n Antwort:'
                                              ],
                                   "passive": ['Prämisse: {premise}, \n Diese Prämisse wird als Wahrheit angenommen. Wird die folgende Aussage durch diese Wahrheit impliziert: {hypothesis}? Mögliche Antworten: \n A ja \n B nein \n C vielleicht \n Antwort:',
                                               'Gegeben die Prämisse: {premise} \n Wird angenommen, dass dies wahr ist: {hypothesis}? Mögliche Antworten: \n A ja \n B nein \n C vielleicht \n Antwort:',
                                               'Gegeben die Prämisse: {premise} \n Wird durch diese Prämisse impliziert, dass dies wahr ist: {hypothesis}? Mögliche Antworten: \n A ja \n B nein \n C vielleicht \n Antwort:',
                                               '{premise} \n Kann gesagt werden, dass: {hypothesis}? Mögliche Antworten: \n A ja \n B nein \n C vielleicht \n Antwort:',
                                               'Diese Prämisse wird als wahr angenommen: {premise}, \n Kann daher das Folgende als wahr betrachtet werden: {hypothesis}? Mögliche Antworten: \n A ja \n B nein \n C vielleicht \n Antwort:',
                                               'Prämisse: {premise} \n Frage: Wird durch diese Prämisse impliziert, dass: {hypothesis}? Mögliche Antworten: \n A ja \n B nein \n C vielleicht \n Antwort:',
                                               'Diese Prämisse wird als wahr angenommen: {premise} \n Kann daraus geschlossen werden, dass: {hypothesis}? Mögliche Antworten: \n A ja \n B nein \n C vielleicht \n Antwort:',
                                               '{premise} \n Basierend auf dem vorherigen Abschnitt, wird das Folgende impliziert: {hypothesis}? Mögliche Antworten: \n A ja \n B nein \n C vielleicht \n Antwort:',
                                               '{premise} \n Basierend auf den obigen Informationen, kann daraus geschlossen werden, dass: {hypothesis}? Mögliche Antworten: \n A ja \n B nein \n C vielleicht \n Antwort:',
                                               'Folgendes wird betrachtet: {premise} \n Wird das Folgende durch den vorherigen Text impliziert: {hypothesis}? Mögliche Antworten: \n A ja \n B nein \n C vielleicht \n Antwort:'
                                               ],
                                   "auxiliary": ['Nehmen Sie das Folgende als wahr an: {premise} \n Impliziert diese Wahrheit die folgende Aussage: {hypothesis}? Mögliche Antworten: \n A ja \n B nein \n C vielleicht \n Antwort:',
                                                 'Gegeben: {premise}, \n Gehen wir davon aus, dass es wahr ist, dass: {hypothesis}? Mögliche Antworten: \n A ja \n B nein \n C vielleicht \n Antwort:',
                                                 'Nehmen Sie an, dass das Folgende wahr ist: {premise}, \n Ist es daher zwingend, dass: {hypothesis}? Mögliche Antworten: \n A ja \n B nein \n C vielleicht \n Antwort:',
                                                 '{premise} \n Frage: Impliziert der vorherige Text, dass: {hypothesis}? Mögliche Antworten: \n A ja \n B nein \n C vielleicht \n Antwort:',
                                                 '{premise} \n Basierend auf dem vorherigen Abschnitt, wird daraus geschlossen, dass: {hypothesis}? Mögliche Antworten: \n A ja \n B nein \n C vielleicht \n Antwort:',
                                                 '{premise} \n Aus den vorherigen Informationen ergibt sich, dass dies impliziert wird: {hypothesis}? Mögliche Antworten: \n A ja \n B nein \n C vielleicht \n Antwort:',
                                                 'Nehmen Sie das Folgende als wahr an: {premise}, \n Wird die folgende Aussage durch diese Wahrheit bedingt: {hypothesis}? Mögliche Antworten: \n A ja \n B nein \n C vielleicht \n Antwort:',
                                                 'Angenommen, dies ist wahr: {premise}. \n Kann daraus geschlossen werden, dass: {hypothesis}? Mögliche Antworten: \n A ja \n B nein \n C vielleicht \n Antwort:',
                                                 'Es wird angenommen, dass es wahr ist: {premise} \n Daher nehmen wir auch an, dass: {hypothesis}? Mögliche Antworten: \n A ja \n B nein \n C vielleicht \n Antwort:',
                                                 '{premise} \n Sagen wir, dass das Vorherige das Folgende bedingt: {hypothesis}? Mögliche Antworten: \n A ja \n B nein \n C vielleicht \n Antwort:'
                                                 ],
                                   "modal": ['Nehmen Sie das Folgende als wahr an: {premise} \n Könnte diese Wahrheit die folgende Aussage implizieren: {hypothesis}? Mögliche Antworten: \n A ja \n B nein \n C vielleicht \n Antwort:',
                                             'Gegeben: {premise} \n Können wir davon ausgehen, dass es wahr ist, dass: {hypothesis}? Mögliche Antworten: \n A ja \n B nein \n C vielleicht \n Antwort:',
                                             'Wir nehmen an, dass das Folgende wahr sein muss: {premise}, \n Muss es daher zwingend sein, dass: {hypothesis}? Mögliche Antworten: \n A ja \n B nein \n C vielleicht \n Antwort:',
                                             '{premise} \n Frage: Würde der vorherige Text implizieren, dass: {hypothesis}? Mögliche Antworten: \n A ja \n B nein \n C vielleicht \n Antwort:',
                                             '{premise} \n Basierend auf dem vorherigen Abschnitt, könnte daraus geschlossen werden, dass: {hypothesis}? Mögliche Antworten: \n A ja \n B nein \n C vielleicht \n Antwort:',
                                             '{premise} \n Aus den vorherigen Informationen heraus, könnte dies impliziert werden: {hypothesis}? Mögliche Antworten: \n A ja \n B nein \n C vielleicht \n Antwort:',
                                             'Nehmen Sie das Folgende als wahr an: {premise}, \n Sollte die folgende Aussage durch diese Wahrheit bedingt sein: {hypothesis}? Mögliche Antworten: \n A ja \n B nein \n C vielleicht \n Antwort:',
                                             'Angenommen, dies ist wahr: {premise}. \n Könnte daraus geschlossen werden, dass: {hypothesis}? Mögliche Antworten: \n A ja \n B nein \n C vielleicht \n Antwort:',
                                             'Es wird angenommen, dass es wahr ist: {premise} \n Sollten wir Daher auch annehmen, dass: {hypothesis}? Mögliche Antworten: \n A ja \n B nein \n C vielleicht \n Antwort:',
                                             '{premise} \n Können wir sagen, dass das Vorherige das Folgende bedingt: {hypothesis}? Mögliche Antworten: \n A ja \n B nein \n C vielleicht \n Antwort:'
                                             ],
                                   "common": ['Nehmen wir an, es ist wahr, dass: {premise} \n Daher impliziert es auch: {hypothesis}? Mögliche Antworten: \n A ja \n B nein \n C vielleicht \n Antwort:',
                                              '{premise} \n Basierend auf diesen Informationen, wird die folgende Aussage impliziert: {hypothesis}? Mögliche Antworten: \n A ja \n B nein \n C vielleicht \n Antwort:',
                                              '{premise} \n Frage: Würde dies auch bedeuten, dass: {hypothesis}? Mögliche Antworten: \n A ja \n B nein \n C vielleicht \n Antwort:',
                                              'Angenommen: {premise} \n Kann daraus geschlossen werden, dass: {hypothesis}? Mögliche Antworten: \n A ja \n B nein \n C vielleicht \n Antwort:',
                                              '{premise} \n Basierend auf dem vorherigen Abschnitt, muss die folgende Aussage gelten: {hypothesis}? Mögliche Antworten: \n A ja \n B nein \n C vielleicht \n Antwort:',
                                              'Angenommen, das Folgende ist wahr: {premise} \n Können wir daraus schließen, dass: {hypothesis}? Mögliche Antworten: \n A ja \n B nein \n C vielleicht \n Antwort:',
                                              'Nehmen wir das Folgende als Wahrheit an: {premise} \n Könnte die folgende Aussage daraus abgeleitet werden: {hypothesis}? Mögliche Antworten: \n A ja \n B nein \n C vielleicht \n Antwort:'
                                              ],
                                   "rare_synonyms": ['Stellen Sie die folgende Behauptung auf: {premise} \n Folglich impliziert es auch: {hypothesis}? Mögliche Antworten: \n A ja \n B nein \n C vielleicht \n Antwort:',
                                                     '{premise} \n Gestützt auf diesen Kenntnisse, wird die folgende Annahme beinhaltet: {hypothesis}? Mögliche Antworten: \n A ja \n B nein \n C vielleicht \n Antwort:',
                                                     '{premise} \n Anliegen: Würde dies auch signalisieren, dass: {hypothesis}? Mögliche Antworten: \n A ja \n B nein \n C vielleicht \n Antwort:',
                                                     'Vorausgesetzt: {premise} \n Kann daraufhin geschlussfolgert werden, dass: {hypothesis}? Mögliche Antworten: \n A ja \n B nein \n C vielleicht \n Antwort:',
                                                     '{premise} \n Ausgehend von dem oben genannten Segment, muss die folgende Stellungnahme gelten: {hypothesis}? Mögliche Antworten: \n A ja \n B nein \n C vielleicht \n Antwort:',
                                                     'Vorausgesetzt, das Anschließende ist wahr: {premise} \n Können wir infolgedessen ableiten, dass: {hypothesis}? Mögliche Antworten: \n A ja \n B nein \n C vielleicht \n Antwort:',
                                                     'Betrachten Sie das Anschließende als Wahrheit: {premise} \n Könnte die hierauffolgende Erzählung infolgedessen abgezogen werden: {hypothesis}? Mögliche Antworten: \n A ja \n B nein \n C vielleicht \n Antwort:'
                                                     ],
                                   "identical_modal": ["Angesichts der: {premise} \n Dürfen wir annehmen, dass: {hypothesis}? Mögliche Antworten: \n A ja \n B nein \n C vielleicht \n Antwort:",
                                                       "Angesichts der: {premise} \n Können wir annehmen, dass: {hypothesis}? Mögliche Antworten: \n A ja \n B nein \n C vielleicht \n Antwort:",
                                                       "Angesichts der: {premise} \n Möchten wir annehmen, dass: {hypothesis}? Mögliche Antworten: \n A ja \n B nein \n C vielleicht \n Antwort:",
                                                       "Angesichts der: {premise} \n Müssen wir annehmen, dass: {hypothesis}? Mögliche Antworten: \n A ja \n B nein \n C vielleicht \n Antwort:",
                                                       "Angesichts der: {premise} \n Wollen wir annehmen, dass: {hypothesis}? Mögliche Antworten: \n A ja \n B nein \n C vielleicht \n Antwort:",
                                                       "Angesichts der: {premise} \n Sollen wir annehmen, dass: {hypothesis}? Mögliche Antworten: \n A ja \n B nein \n C vielleicht \n Antwort:",
                                                       ]}},

                    "fr": {"SA": {"active": ["Critique: {content} \n Cette critique est-elle positive? Réponses possibles: \n A oui \n B non \n Reponse:",
                                             "Critique: {content} \n Est-ce que cette critique donne une impression positive? Réponses possibles: \n A oui \n B non \n Réponse:",
                                             "Critique: {content} \n L'utilisateur a-t-il rédigé une critique positive? Réponses possibles: \n A oui \n B non \n Réponse:",
                                             "Critique: {content} \n Est-ce que cette critique de ce produit reflète la positivité? Réponses possibles: \n A oui \n B non \n Réponse:",
                                             "Critique: {content} \n L'utilisateur recommande-t-il le produit? Réponses possibles: \n A oui \n B non \n Réponse:",
                                             "Critique: {content} \n Est-ce que cette critique du produit transmet un sentiment positif? Réponses possibles: \n A oui \n B non \n Réponse:",
                                             "Critique: {content} \n Cette critique du produit a-t-elle un ton positif? Réponses possibles: \n A oui \n B non \n Réponse:",
                                             "Critique: {content} \n Voici un avis sur un produit laissé par un client. Considérez-vous cet avis comme positif? Réponses possibles: \n A oui \n B non \n Réponse:",
                                             "Critique: {content} \n Pouvez-vous dire que cette critique présente le produit sous un jour positif? Réponses possibles: \n A oui \n B non \n Réponse:",
                                             "Critique: {content} \n Est-ce que le critique exprime un sentiment positif envers le produit? Réponses possibles: \n A oui \n B non \n Réponse:"
                                             ],
                                  "passive": ["Critique: {content} \n Est-ce que cette critique est considérée comme positive? Réponses possibles: \n A oui \n B non \n Reponse:",
                                              "Critique: {content} \n Est-ce que cette critique est considérée comme ayant un ton positif? Réponses possibles: \n A oui \n B non \n Réponse:",
                                              "Critique: {content} \n Est-ce que cette critique a été rédigée de manière positive par l'utilisateur? Réponses possibles: \n A oui \n B non \n Réponse:",
                                              "Critique: {content} \n Cette critique du produit est-elle caractérisée par la positivité? Réponses possibles: \n A oui \n B non \n Réponse:",
                                              "Critique: {content} \n La critique écrite par l'utilisateur recommande-t-elle le produit? Réponses possibles: \n A oui \n B non \n Réponse:",
                                              "Critique: {content} \n Est-ce que le sentiment positif est véhiculé par cet avis sur le produit? Réponses possibles: \n A oui \n B non \n Réponse:",
                                              "Critique: {content} \n Cette critique est-elle rédigée avec un ton positif? Réponses possibles: \n A oui \n B non \n Réponse:",
                                              "Critique: {content} \n Voici un avis sur un produit laissé par un client. Est-ce que cette critique est considérée comme positive? Réponses possibles: \n A oui \n B non \n Réponse:",
                                              "Critique: {content} \n Pouvez-vous dire que le produit dans cette critique est présenté sous un jour positif? Réponses possibles: \n A oui \n B non \n Réponse:",
                                              "Critique: {content} \n Est-ce que le produit est considéré positivement par le critique? Réponses possibles: \n A oui \n B non \n Réponse:"
                                              ],
                                  "auxiliary": ["Critique: {content} \n Cette critique est-elle positive? Réponses possibles: \n A oui \n B non \n Reponse:",
                                                "Critique: {content} \n Considérez-vous cette critique comme positive? Réponses possibles: \n A oui \n B non \n Réponse:",
                                                "Critique: {content} \n L'utilisateur a-t-il rédigé une critique positive? Réponses possibles: \n A oui \n B non \n Réponse:",
                                                "Critique: {content} \n D'après cette critique, est-ce que l'utilisateur recommande le produit? Réponses possibles: \n A oui \n B non \n Réponse:",
                                                "Critique: {content} \n Est-ce que cette critique du produit transmet un sentiment positif? Réponses possibles: \n A oui \n B non \n Réponse:",
                                                "Critique: {content} \n Cette critique du produit a-t-elle un ton positif? Réponses possibles: \n A oui \n B non \n Réponse:",
                                                "Critique: {content} \n Voici un avis sur un produit laissé par un client. Considérez-vous cette critique comme positive? Réponses possibles: \n A oui \n B non \n Réponse:",
                                                "Critique: {content} \n Est-ce que le critique exprime un sentiment positif envers le produit? Réponses possibles: \n A oui \n B non \n Réponse:",
                                                "Critique: {content} \n Est-ce que l'utilisateur pense positivement du produit? Réponses possibles: \n A oui \n B non \n Réponse:",
                                                "Critique: {content} \n Est-ce que ce critique exprime un sentiment positif? Réponses possibles: \n A oui \n B non \n Réponse:"
                                                ],
                                  "modal": ["Critique: {content} \n Est-ce que cette critique pourrait être positive? Réponses possibles: \n A oui \n B non \n Reponse:",
                                            "Critique: {content} \n Pourriez-vous considérer cette critique comme positive? Réponses possibles: \n A oui \n B non \n Réponse:",
                                            "Critique: {content} \n L'utilisateur aurait-il pu rédiger une critique positive? Réponses possibles: \n A oui \n B non \n Réponse:",
                                            "Critique: {content} \n D'après cette critique, est-ce que l'utilisateur pourrait recommander le produit? Réponses possibles: \n A oui \n B non \n Réponse:",
                                            "Critique: {content} \n Est-ce que cette critique du produit pourrait transmettre un sentiment positif? Réponses possibles: \n A oui \n B non \n Réponse:",
                                            "Critique: {content} \n Est-ce que cette critique du produit pourrait avoir un ton positif? Réponses possibles: \n A oui \n B non \n Réponse:",
                                            "Critique: {content} \n Voici un avis sur un produit laissé par un client. Pouvez-vous considérer cette critique comme positive? Réponses possibles: \n A oui \n B non \n Réponse:",
                                            "Critique: {content} \n Est-ce que le critique pourrait exprimer un sentiment positif envers le produit? Réponses possibles: \n A oui \n B non \n Réponse:",
                                            "Critique: {content} \n L'utilisateur doit-il penser positivement du produit? Réponses possibles: \n A oui \n B non \n Réponse:",
                                            "Critique: {content} \n Est-ce que ce commentaire doit exprimer un sentiment positif? Réponses possibles: \n A oui \n B non \n Réponse:"
                                            ],
                                  "common": ['Critique: {content} \n Considérez-vous cette critique comme positive? Réponses possibles: \n A oui \n B non \n Réponse:',
                                             "Critique: {content} \n L'utilisateur a-t-il rédigé une critique positive? Réponses possibles: \n A oui \n B non \n Réponse:",
                                             'Critique: {content} \n Est-ce que le critique exprime un sentiment positif envers le produit? Réponses possibles: \n A oui \n B non \n Réponse:',
                                             'Critique: {content} \n Voici un avis sur un produit laissé par un client. Est-ce que cette critique peut être classée comme positive? Réponses possibles: \n A oui \n B non \n Réponse:',
                                             "Critique: {content} \n D'après cette critique, est-ce que l'utilisateur pourrait recommander le produit? Réponses possibles: \n A oui \n B non \n Réponse:",
                                             'Critique: {content} \n Diriez-vous que cette critique est positive? Réponses possibles: \n A oui \n B non \n Réponse:',
                                             'Critique: {content} \n Est-ce que cette critique du produit a un ton positif? Réponses possibles: \n A oui \n B non \n Réponse:'
                                             ],
                                  "rare_synonyms": ["Critique: {content} \n Estimes-tu cette critique comme étant favorable? Réponses possibles: \n A oui \n B non \n Réponse:",
                                                    "Critique: {content} \n L'acheteur a-t-il rédigé une critique positive? Réponses possibles: \n A oui \n B non \n Réponse:",
                                                    "Critique: {content} \n Est-ce que le critique connote une disposition positive envers le produit? Réponses possibles: \n A oui \n B non \n Réponse:",
                                                    "Critique: {content} \n Voici un avis sur une marchandise fabriquée par un acheteur. Est-ce que cette critique peut être catégorisée comme positive? Réponses possibles: \n A oui \n B non \n Réponse:",
                                                    "Critique: {content} \n En examinant cette critique, est-ce que l'acheteur pourrait faire la promotion du produit? Réponses possibles: \n A oui \n B non \n Réponse:",
                                                    "Critique: {content} \n Penserais-tu que la critique précédente est positive? Réponses possibles: \n A oui \n B non \n Réponse:",
                                                    "Critique: {content} \n Est-ce que cette critique de la marchandise a un ton positif? Réponses possibles: \n A oui \n B non \n Réponse:"
                                                    ],
                                  "identical_modal": ["Critique: {content} \n Pourrait-on considérer cette critique comme positive? Réponses possibles: \n A oui \n B non \n Réponse:",
                                                      "Critique: {content} \n Peut-on considérer cette critique comme positive? Réponses possibles: \n A oui \n B non \n Réponse:",
                                                      "Critique: {content} \n Doit-on considérer cette critique comme positive? Réponses possibles: \n A oui \n B non \n Réponse:",
                                                      "Critique: {content} \n Saurait-on considérer cette critique comme positive? Réponses possibles: \n A oui \n B non \n Réponse:",
                                                      "Critique: {content} \n Il faudrait considérer cette critique comme positive? Réponses possibles: \n A oui \n B non \n Réponse:",
                                                      "Critique: {content} \n Oserait-on considérer cette critique comme positive? Réponses possibles: \n A oui \n B non \n Réponse:"
                                                      ]},

                           "NLI": {"active": ["Prémisse: {premise} \n Prends cette prémisse comme vérité. Cette vérité implique-t-elle l'affirmation suivante: {hypothesis}? Réponses possibles: \n A oui \n B non \n C peut-être \n Réponse:",
                                              "Étant donné la prémisse: {premise} \n Supposons-nous que cela soit vrai: {hypothesis}? Réponses possibles: \n A oui \n B non \n C peut-être \n Réponse:",
                                              "Étant donné la prémisse: {premise} \n Est-ce que cette prémisse laisse entendre que cela est vrai: {hypothesis}? Réponses possibles: \n A oui \n B non \n C peut-être \n Réponse:",
                                              "{premise} \n Peut-on dire que: {hypothesis}? Réponses possibles: \n A oui \n B non \n C peut-être \n Réponse:",
                                              "Supposez que cette prémisse soit vraie: {premise}, \n Par conséquent, est-ce que ce qui suit est vrai: {hypothesis}? Réponses possibles: \n A oui \n B non \n C peut-être \n Réponse:",
                                              "Prémisse: {premise} \n Est-ce que cette prémisse implique que: {hypothesis}? Réponses possibles: \n A oui \n B non \n C peut-être \n Réponse:",
                                              "Supposons que cette prémisse soit vraie: {premise} \n Peut-on déduire que: {hypothesis}? Réponses possibles: \n A oui \n B non \n C peut-être \n Réponse:",
                                              "{premise} \n Sur la base du passage précédent, cela entraîne-t-il ce qui suit: {hypothesis}? Réponses possibles: \n A oui \n B non \n C peut-être \n Réponse:",
                                              "{premise} \n En se basant sur les informations ci-dessus, peut-on déduire ce qui suit: {hypothesis}? Réponses possibles: \n A oui \n B non \n C peut-être \n Réponse:",
                                              "Considérez ce qui suit: {premise} \n Le texte précédent entraîne-t-il ce qui suit: {hypothesis}? Réponses possibles: \n A oui \n B non \n C peut-être \n Réponse:"
                                              ],
                                   "passive": ["Prémisse: {premise}, \n Cette prémisse est considérée comme étant vraie. Le fait suivant est-il entraîné par cette vérité: {hypothesis}? Réponses possibles: \n A oui \n B non \n C peut-être \n Réponse:",
                                               "Étant donné la prémisse: {premise} \n Est-il supposé que ceci est vrai: {hypothesis}? Réponses possibles: \n A oui \n B non \n C peut-être \n Réponse:",
                                               "Étant donné la prémisse {premise} \n Est-il déduit par cette prémisse que ceci est vrai: {hypothesis}? Réponses possibles: \n A oui \n B non \n C peut-être \n Réponse:",
                                               "{premise} \n Est-il possible de dire que: {hypothesis}? Réponses possibles: \n A oui \n B non \n C peut-être \n Réponse:",
                                               "Cette prémisse est supposée être vraie: {premise}, \n Par conséquent, peut-on considérer ce qui suit comme étant vrai: {hypothesis}? Réponses possibles: \n A oui \n B non \n C peut-être \n Réponse:",
                                               "Prémisse: {premise} \n Est-il sous-entendu par cette prémisse que: {hypothesis}? Réponses possibles: \n A oui \n B non \n C peut-être \n Réponse:",
                                               "Cette prémisse est supposée être vraie: {premise} \n Peut-il être déduit que: {hypothesis}? Réponses possibles: \n A oui \n B non \n C peut-être \n Réponse:",
                                               "{premise} \n En se basant sur le passage précédent, est-ce que ce qui suit est impliqué: {hypothesis}? Réponses possibles: \n A oui \n B non \n C peut-être \n Réponse:",
                                               "{premise} \n En se basant sur les informations ci-dessus, est-ce que ce qui suit peut être déduit: {hypothesis}? Réponses possibles: \n A oui \n B non \n C peut-être \n Réponse:",
                                               "Ce qui suit est considéré: {premise} \n Est-ce que ce qui suit est impliqué par le texte précédent: {hypothesis}? Réponses possibles: \n A oui \n B non \n C peut-être \n Réponse:"
                                               ],
                                   "auxiliary": ["Prenez ce qui suit comme vérité: {premise} \n Cette vérité implique-t-elle l'affirmation suivante: {hypothesis}? Réponses possibles: \n A oui \n B non \n C peut-être \n Réponse:",
                                                 "Étant donné: {premise}, \n Supposons-nous que cela soit vrai que: {hypothesis}? Réponses possibles: \n A oui \n B non \n C peut-être \n Réponse:",
                                                 "Supposez que ce qui suit est vrai: {premise}, \n Par conséquent, est-il impliqué que: {hypothesis}? Réponses possibles: \n A oui \n B non \n C peut-être \n Réponse:",
                                                 "{premise} \n Le texte précédent implique-t-il que: {hypothesis}? Réponses possibles: \n A oui \n B non \n C peut-être \n Réponse:",
                                                 "{premise} \n En se basant sur le passage précédent, est-il inféré que: {hypothesis}? Réponses possibles: \n A oui \n B non \n C peut-être \n Réponse:",
                                                 "{premise} \n En se basant sur les informations précédentes, est-ce que cela est implicite: {hypothesis}? Réponses possibles: \n A oui \n B non \n C peut-être \n Réponse:",
                                                 "Prenez ce qui suit comme vérité: {premise}, \n La déclaration suivante est-elle engendrée par cette vérité: {hypothesis}? Réponses possibles: \n A oui \n B non \n C peut-être \n Réponse:",
                                                 "Supposons que ceci soit vrai: {premise}. \n Est-il possible de déduire que: {hypothesis}? Réponses possibles: \n A oui \n B non \n C peut-être \n Réponse:",
                                                 "On suppose que c'est vrai que: {premise} \n Par conséquent, supposons-nous également que: {hypothesis}? Réponses possibles: \n A oui \n B non \n C peut-être \n Réponse:",
                                                 "{premise} \n Disons-nous que le précédent implique le suivant: {hypothesis}? Réponses possibles: \n A oui \n B non \n C peut-être \n Réponse:"
                                                 ],
                                   "modal": ["Prenez ce qui suit comme vérité: {premise} \n Est-ce que cette vérité pourrait impliquer l'affirmation suivante: {hypothesis}? Réponses possibles: \n A oui \n B non \n C peut-être \n Réponse:",
                                             "Étant donné: {premise} \n Pouvons-nous supposer que c'est vrai que: {hypothesis}? Réponses possibles: \n A oui \n B non \n C peut-être \n Réponse:",
                                             "Supposez que ce qui suit est vrai: {premise}, \n Par conséquent, doit-il être impliqué que: {hypothesis}? Réponses possibles: \n A oui \n B non \n C peut-être \n Réponse:",
                                             "{premise} \n  Est-ce que le texte précédent pourrait laisser entendre que: {hypothesis}? Réponses possibles: \n A oui \n B non \n C peut-être \n Réponse:",
                                             "{premise} \n En se basant sur le passage précédent, pourrait-on en déduire que: {hypothesis}? Réponses possibles: \n A oui \n B non \n C peut-être \n Réponse:",
                                             "{premise} \n En se basant sur les informations précédentes, cela peut-il être sous-entendu: {hypothesis}? Réponses possibles: \n A oui \n B non \n C peut-être \n Réponse:",
                                             "Prenez ce qui suit comme vérité: {premise}, \n Devrait-on considérer que l'énoncé suivant est impliqué par cette vérité: {hypothesis}? Réponses possibles: \n A oui \n B non \n C peut-être \n Réponse:",
                                             "Supposons que ceci soit vrai: {premise}. \n Pourrait-on inférer que: {hypothesis}? Réponses possibles: \n A oui \n B non \n C peut-être \n Réponse:",
                                             "On suppose que c'est vrai que: {premise} \n Par conséquent, devrions-nous également supposer que: {hypothesis}? Réponses possibles: \n A oui \n B non \n C peut-être \n Réponse:",
                                             "{premise} \n Pouvons-nous dire que le précédent implique le suivant: {hypothesis}? Réponses possibles: \n A oui \n B non \n C peut-être \n Réponse:"
                                             ],
                                   "common": ["Supposons que c'est vrai: {premise} \n Par conséquent, est-ce que cela implique aussi: {hypothesis}? Réponses possibles: \n A oui \n B non \n C peut-être \n Réponse:",
                                              "{premise} \n En se basant sur ces informations, est-ce que l'affirmation suivante est impliquée: {hypothesis}? Réponses possibles: \n A oui \n B non \n C peut-être \n Réponse:",
                                              "{premise} \n Est-ce que cela impliquerait également: {hypothesis}? Réponses possibles: \n A oui \n B non \n C peut-être \n Réponse:",
                                              "Supposons que {premise} \n Peut-on en déduire que: {hypothesis}? Réponses possibles: \n A oui \n B non \n C peut-être \n Réponse:",
                                              "{premise} \n En se basant sur le passage précédent, est-ce que l'affirmation suivante doit être vraie: {hypothesis}? Réponses possibles: \n A oui \n B non \n C peut-être \n Réponse:",
                                              "Supposons que ce qui suit est vrai: {premise} \n Peut-on en déduire que: {hypothesis}? Réponses possibles: \n A oui \n B non \n C peut-être \n Réponse:",
                                              "Prenons ceci comme vérité: {premise} \n Est-ce que l'affirmation suivante pourrait en découler: {hypothesis}? Réponses possibles: \n A oui \n B non \n C peut-être \n Réponse:"
                                              ],
                                   "rare_synonyms": ["Présumez que ce qui suit est véridique: {premise} \n En conséquence, est-ce que cela entraîne également: {hypothesis}? Réponses possibles: \n A oui \n B non \n C peut-être \n Réponse:",
                                                     "{premise} \n Fondé sur ces informations, est-ce que la postulation suivante est impliquée: {hypothesis}? Réponses possibles: \n A oui \n B non \n C peut-être \n Réponse:",
                                                     "{premise} \n Cela signifierait-il en outre que {hypothesis}? Réponses possibles: \n A oui \n B non \n C peut-être \n Réponse:",
                                                     "Présumez que {premise} \n Peut-on conclure que: {hypothesis}? Réponses possibles: \n A oui \n B non \n C peut-être \n Réponse:",
                                                     "{premise} \n En partant du passage susmentionné, est-ce que ce qui suit doit être maintenu: {hypothesis}? Réponses possibles: \n A oui \n B non \n C peut-être \n Réponse:",
                                                     "Présupposez que ce qui suit est vrai: {premise} \n Peut-on conclure que: {hypothesis}? Réponses possibles: \n A oui \n B non \n C peut-être \n Réponse:",
                                                     "Percevez ce qui suit comme vérité: {premise} \n Est-ce que la proclamation ultérieure pourrait en découler: {hypothesis}? Réponses possibles: \n A oui \n B non \n C peut-être \n Réponse:",
                                                     ],
                                   "identical_modal": ["Étant donné: {premise} \n Pouvons-nous supposer que cela est vrai: {hypothesis}? Réponses possibles: \n A oui \n B non \n C peut-être \n Réponse:",
                                                       "Étant donné: {premise} \n Devrions-nous supposer que cela est vrai: {hypothesis}? Réponses possibles: \n A oui \n B non \n C peut-être \n Réponse:",
                                                       "Étant donné: {premise} \n Pourrions-nous supposer que cela est vrai: {hypothesis}? Réponses possibles: \n A oui \n B non \n C peut-être \n Réponse:",
                                                       "Étant donné: {premise} \n Faudrait-il supposer que cela est vrai: {hypothesis}? Réponses possibles: \n A oui \n B non \n C peut-être \n Réponse:",
                                                       "Étant donné: {premise} \n Saurions-nous supposer que cela est vrai: {hypothesis}? Réponses possibles: \n A oui \n B non \n C peut-être \n Réponse:",
                                                       ]}}}
